POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3Mjc0NzgyMzMsInVzZXJJZCI6MX0.DjrTmIzVgHDynEJIzPsuFWogGzFF87pVn_Y86U8MziQ

{ 
 "name": "new event 1!!",
 "description": "another event",
 "location": "NEW YORK",
 "dateTime": "2025-01-01T15:30:00.000Z"
}