GET http://localhost:8080/events/registered
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ld3VzZXJAdGVzdC5jb20iLCJleHAiOjE3Mjc0Nzk5ODcsInVzZXJJZCI6M30.2OgWFxJx-J50mTho0umTgP4H8wD9EU5CiQ3UrXX-gus