POST http://localhost:8080/events/1/register
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ld3VzZXJAdGVzdC5jb20iLCJleHAiOjE3Mjc0Nzg3NjYsInVzZXJJZCI6M30.Cx6cfJ37mE8rtBgNxxT7je13RhzKXJLFgfuf0W3xkfc