PUT http://localhost:8080/events/1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3Mjc0NzM4OTAsInVzZXJJZCI6MX0.eVD2E2hj2uYFCfIMrzhqoviLSOk7Q7LDaIZPQsblcfs

{
  "name": "Updated Event",
  "description": "Updated Description",
  "location": "Rio de Janeiro",
  "dateTime": "2022-12-31T23:59:59.999Z" 
}